#!/bin/sh

#SPEED=1
SPEED=5
MIN=5

V1=$(amixer get Master |grep "Front Left:" |field 5 | cut -d'[' -f2 | cut -d'%' -f1)
V2=$(python3 -c "print($V1 - $SPEED) if (($V1 - $SPEED) > $MIN) else print($MIN)")

amixer set Master "$V2%" > /dev/null

notify-send -t 500 "$V2%" &
