#!/bin/sh
if [ -z "$1" ]; then
    echo "Usage: $0 name"
    exit
    fi

N="$1"
F="$HOME/.config/autostart/$N.desktop"
if [ -e "$F" ]; then
    echo "$F already exists; bailing out."
    exit
    fi

echo "[Desktop Entry]" > "$F"
echo "Name=$N" >> "$F"
echo "Comment=$N" >> "$F"
echo "Exec=$N" >> "$F"
echo "Icon=$N" >> "$F"
echo "Type=Application" >> "$F"
echo "X-GNOME-Autostart-enabled=true" >> "$F"
echo "X-GNOME-UsesNotifications=true" >> "$F"

