#!/bin/sh

# user home security
for u in rich kathy; do
    rm -vrf \
        /home/$u/.wget-hsts \
        /home/$u/.local/share/recently-used.xbel \
        /home/$u/.xsession-errors.old
    done

# root home
rm -vrf \
    /root/.aptitude/ /root/.cache/ /root/.local/ /root/.synaptic/ /root/.gnupg/ \
    /root/.ssh/

# docs / locales
rm -vrf \
    /usr/share/doc/* /usr/share/help/* \
    /usr/share/gtk-doc/html/* /usr/shaer/bug/ /usr/share/locale/*/

apt clean

updatedb

sync

