#!/bin/sh

export FORCE_UNSAFE_CONFIGURE=1
if [ ! -e conf_idm ]; then
    echo "bash configure --prefix=/usr/local \\" > conf_idm
    echo "    $@ \\" >> conf_idm
    echo '    $@' >> conf_idm
    chmod +x conf_idm
fi

if [ ! -x conf_idm ]; then
    chmod +x ./conf_idm
fi

./conf_idm

