#!/bin/sh

#if [ -z "$(lsblk -f | grep flinuxroot)" ]; then
if [ -z "$(blkid | grep flinuxroot)" ]; then
    echo no flinuxroot found
    exit -1
fi

mount LABEL=linuxroot /media/mnt
mount LABEL=flinuxroot /media/mnt2

cd /media/mnt2

for f in $(root_dirs); do
    sync_dir_del /media/mnt/"$f" ./"$f"
    done

sync_dir_del /media/hd/ media/hd/

cd /

umount /media/mnt
sync
umount /media/mnt2
sync

