#!/bin/sh

# user home security
for u in rich kathy; do
    rm -vrf \
        /home/$u/.wget-hsts \
        /home/$u/.local/share/recently-used.xbel \
        /home/$u/.xsession-errors.old
    done

# root home
rm -vrf \
    /root/.cache/ /root/.local/ /root/.gnupg/ \
    /root/.ssh/

# docs / locales
rm -vrf \
    /usr/share/doc/* /usr/share/help/* \
    /usr/share/gtk-doc/html/* /usr/share/locale/*/


which pacman >& /dev/null && rm -f /var/cache/pacman/pkg/*

updatedb

sync

