#!/bin/sh

PN="$@"
while true; do
    BN="$(ls --color=no "$PN" | dmenu -fn Hack\-14 -l 40)"
    if [ -z "$BN" ]; then
        break
        fi

    if [ ${BN:0:1} == "/" ]; then
        if [ -d "$BN" ]; then
            PN="$BN"
            continue
            fi
        gio open "$BN"
        break
        fi

    FN="$PN"/"$BN"
    if [ -d "$FN" ] || [ ${BN:0:1} == "/" ]; then
        PN="$FN"
        continue
        fi

    gio open "$FN"
    break
    done
 
