#!/bin/sh

[ -n "$1" ] &&\
    D="$1" ||\
    D="."

[ -n "$2" ] &&\
    G="$2" ||\
    G="$(id -g)"

[ -n "$3" ] &&\
    U="$3" ||\
    U="$(id -u)"

chown -R "$U"."$G" "$D"

chmod -R u+w "$D"
chmod -R go+rX "$D"
chmod -R o-w "$D"

