#! /bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

mount -t proc proc /proc
mount -t sysfs sys /sys
mkdir /dev/pts
mount -t devpts pts /dev/pts
mkdir /dev/shm
mount -t tmpfs shm /dev/shm
mount -t tmpfs run /run
mkdir /run/log
mkdir /run/lock
mkdir /run/resolvconf
mkdir /run/dbus
mkdir -p -m 700 /run/user/1000/
chown 1000.1000 /run/user/1000

export HOSTNAME=$(cat /etc/hostname)
hostname "$HOSTNAME"
cat /etc/init/modules.list."$HOSTNAME" | xargs modprobe -a -b

/prebuilt/rescue/syslogd

sysctl --system > /dev/null

mount -o remount,rw LABEL=linuxroot
swapon -a
mount -a

/usr/local/sbin/udevd --daemon
/local/bin/udevadm trigger
/local/bin/udevadm settle

ip link set lo up
/etc/init/wifi_up &

alsactl restore

dbus-daemon --system --fork

/local/bin/console-kit-daemon

pulseaudio --system -D

lightdm &

/etc/rc.local

