#!/bin/sh
IDD="$HOME/.cache/i3bml/"

focus_parent_a_lot () {
    X=0
    while [ "$X" -lt 16 ]; do
        i3-msg -q focus parent
        X=$(($X + 1))
        done
}

case "$BLOCK_BUTTON" in
    1)
        SPLIT=vertical
        ;;
    2)
        FN="$IDD/$1.cid"
        if [ ! -e "$FN" ]; then
            exit -1
            fi

        CID=$(cat "$FN")
        rm -f "$FN"
        i3-msg -q focus $CID
        i3-msg -q kill 
        exit 0
        ;;
    3)
        SPLIT=horizontal
        ;;
    7)
        ;;
    8)
        focus_parent_a_lot
        SPLIT=vertical
        ;;
    9)
        focus_parent_a_lot
        SPLIT=horizontal
        ;;
esac

i3-msg -q split "$SPLIT"

# NOTE: this doesn't currently work with pavucontrol (and..?) or floating windows like dmenu
CID=$(i3-msg open | jq .[].id)
i3-msg -q focus "$CID"
i3-msg -q "exec --no-startup-id $1"

mkdir -p "$IDD"
echo "$CID" > "$IDD/$1.cid"

